### ISSUE TITLE
Add the file name as a comment to the generated SQL statement.

### ISSUE THREAD

**Issue by yuki777** [ray-di/Ray.QueryModule#24]
https://github.com/ray-di/Ray.QueryModule/blob/1.x/src/SqlQueryModule.php#L49

It would be useful to know the SQL Filename when looking at the slow query log.
How about the following, for example, with some options?

```
$sql = "/* {$name} */ " . trim((string) file_get_contents($fullPath));
```

ref : https://cloud.google.com/blog/topics/developers-practitioners/introducing-sqlcommenter-open-source-orm-auto-instrumentation-library

**Comment by koriym** [comment]
Fixed with #25
