### ISSUE TITLE
複数テーブルにまたがるCUDのサポート

### ISSUE THREAD

**Issue by hanahiroAze** [ray-di/Ray.QueryModule#8]
以下のように複数テーブルにまたがるCUDのクエリを発行を1ファイル内で記述できると嬉しいです。

### user
|id|
| --- |
|user id|

### user_detail
|user_id|name|
| --- | --- |
|fk user.id| user's name |

## insert_user.sql

```
insert into user(id) values(:id);
insert into user_detail(id, name) values(:id, :name);
```

**Comment by koriym** [comment]
Released as [0.3.0](https://github.com/ray-di/Ray.QueryModule/releases/tag/0.3.0) !
